// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj1uAIqqvTpH6oozwTUiSdKSqVlgRYPYI',
    appId: '1:515297703367:web:0213d8e04fee6c742c15e2',
    messagingSenderId: '515297703367',
    projectId: 'flutter2-8893a',
    authDomain: 'flutter2-8893a.firebaseapp.com',
    storageBucket: 'flutter2-8893a.firebasestorage.app',
    measurementId: 'G-0N74KX6R3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6ITz7_e76yagCAuM7Ez3kXDLqAQ9IWaM',
    appId: '1:515297703367:android:bfbd73f9d7861d892c15e2',
    messagingSenderId: '515297703367',
    projectId: 'flutter2-8893a',
    storageBucket: 'flutter2-8893a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEsCl0P9UcyMcQYcW1LmhoI051boKSY-Q',
    appId: '1:515297703367:ios:76b76e0c066832882c15e2',
    messagingSenderId: '515297703367',
    projectId: 'flutter2-8893a',
    storageBucket: 'flutter2-8893a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEsCl0P9UcyMcQYcW1LmhoI051boKSY-Q',
    appId: '1:515297703367:ios:76b76e0c066832882c15e2',
    messagingSenderId: '515297703367',
    projectId: 'flutter2-8893a',
    storageBucket: 'flutter2-8893a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj1uAIqqvTpH6oozwTUiSdKSqVlgRYPYI',
    appId: '1:515297703367:web:b7844ba0d7282ca32c15e2',
    messagingSenderId: '515297703367',
    projectId: 'flutter2-8893a',
    authDomain: 'flutter2-8893a.firebaseapp.com',
    storageBucket: 'flutter2-8893a.firebasestorage.app',
    measurementId: 'G-0Z1ZEDX2HR',
  );

}